### ISSUE TITLE
Reason for multiplication and addition after generating outputs

### ISSUE THREAD

**Issue by patrick-han** [ai-tor/PyTorch-CycleGAN#16]
What is the reason for adding 1 and multiplying by 0.5 [here](https://github.com/aitorzip/PyTorch-CycleGAN/blob/67da8f9e2b69bd68763451803c7700aaccc92f18/test#L75) when generating our "fake" outputs. Is this to reverse the effects of ```transforms.Normalize()```?

**Comment by Mahlagha** [comment]
Right, it is equivalent to multiplying by sigma, and then adding the mean.
