### ISSUE TITLE
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

### ISSUE THREAD

**Issue by youngjaeshin** [ai-tor/PyTorch-CycleGAN#21]
Thanks for providing great codes for cycleGAN.
Firstly, I changed code in models.py
return F.avg_pool2d(x, x.size()[2:]).view(x.size()[0],-1) -> remove -1
because of UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])) issue.
After I fix it, I got another issue 'RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]'

Could you comment on this issue?

**Comment by lxycopper** [comment]
I met with the same probelm, waiting for comments.

**Comment by Lornatang** [comment]
@youngjaeshin 
@lxycopper 
This error will be thrown if the image format is not correct when reading the image.
My solution is to delete some abnormal pictures. If you need, I will send the processed data set to Baidu cloud.

**Comment by wbchief** [comment]
Now I also meet the problem, Can you send the processed data set to me? Thanks.

**Comment by wbchief** [comment]
Now I also meet the problem, Can you send the processed data set to me? Thanks. @Lornatang

**Comment by Lornatang** [comment]
You just need to download the link, put it in the 'dataset' directory, and extract it.
url: https://pan.baidu.com/s/1mRF9Ft3aUG_DB1aW4793-Q  passwd: ebvt
You can refer to my project modified by the author, which is more easy to use and readable. See [CycleGAN_PyTorch](https://github.com/Lornatang/CycleGAN_PyTorch)

**Comment by wbchief** [comment]
Thanks.

**Comment by alexander-soare** [comment]
@Lornatang thanks for this. Could I ask what the actual formatting issues were?

**Comment by Lornatang** [comment]
@alexander-soare 
Channel error of image, non-standard RGB format.

**Comment by ZunxiaoXu** [comment]
@Lornatang I’m sorry to find that the link you shared is invalid. Could you please share it again, thank you very much

**Comment by Lornatang** [comment]
@893205894 
Link：https://pan.baidu.com/s/1LbxlYed7oHSOJtRWm38y5A 
passwd：cddr

**Comment by ZunxiaoXu** [comment]
Thinks！
